"""empty message

Revision ID: 3387851b78fa
Revises: 
Create Date: 2017-08-30 18:12:11.756712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3387851b78fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Unicode(length=100), nullable=False),
    sa.Column('message', sa.UnicodeText(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
