"""empty message

Revision ID: ec509f4d3408
Revises: 3387851b78fa
Create Date: 2017-09-01 07:00:28.971871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec509f4d3408'
down_revision = '3387851b78fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('filename', sa.Unicode(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'filename')
    # ### end Alembic commands ###
