"""empty message

Revision ID: 57b2dc73f1a5
Revises: a75e5712bea1
Create Date: 2017-08-28 08:43:41.745791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b2dc73f1a5'
down_revision = 'a75e5712bea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file', sa.Column('comment', sa.UnicodeText(), nullable=True))
    op.add_column('user_file', sa.Column('contest', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_file', 'contest')
    op.drop_column('user_file', 'comment')
    # ### end Alembic commands ###
