"""empty message

Revision ID: f4826b7668d3
Revises: 
Create Date: 2017-08-26 16:02:12.992228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4826b7668d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filedir', sa.Unicode(), nullable=True),
    sa.Column('filename', sa.Unicode(), nullable=True),
    sa.Column('orig_name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_file')
    # ### end Alembic commands ###
